# Sidekiqの設定ファイル
# 環境変数 SIDEKIQ_CONCURRENCY を使用して並行性を設定可能
# 例: SIDEKIQ_CONCURRENCY=25 bundle exec sidekiq

# 並行実行数（デフォルト: 10）- 環境変数で上書き可能
:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 10).to_i %>
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:max_retries: 5

# キューとその優先度 (数値が大きいほど優先度が高い)
:queues:
  - [critical, 3]  # 最優先キュー
  - [default, 2]   # 標準キュー
  - [mailers, 2]   # メール送信キュー
  - [low, 1]       # 優先度低キュー

# Max number of jobs to fetch at once
:fetch: 3

# デバッグログも有効にする場合は以下を有効化
# :verbose: true

# スケジュール設定（sidekiq-scheduler 5.0.6形式）
:scheduler:
  :schedule:
    update_ticket_type_status:
      cron: '*/10 * * * *'  # 10分ごとに実行
      class: UpdateTicketTypeStatusJob
      queue: low
      description: "チケットタイプの販売状態を自動更新するジョブ" 