name: "TODO to Issue"

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      # 自動生成ファイルや頻繁に変更されるファイルを除外
      - '**/*.lock'
  # 毎週月曜日の午前3時（UTC）に実行
  schedule:
    - cron: '0 3 * * 1'

jobs:
  todo:
    runs-on: ubuntu-latest
    # GitHub IssueへのWrite権限を追加
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 差分検出のために完全履歴が必要

      # TODOコメントをIssue化
      - name: Convert TODO / FIXME to Issues
        uses: alstr/todo-to-issue-action@v5
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

          IDENTIFIERS: |
            [
              {"name": "TODO", "labels": ["todo"]},
              {"name": "todo", "labels": ["todo"]},
              {"name": "TODO\\(!enhancement\\)", "labels": ["todo", "enhancement"]},
              {"name": "TODO\\(!security\\)", "labels": ["todo", "security"]},
              {"name": "TODO\\(!feature\\)", "labels": ["todo", "feature"]},
              {"name": "TODO\\(!urgent\\)", "labels": ["todo", "urgent"]},
              {"name": "TODO\\(!backend\\)", "labels": ["todo", "backend"]},
              {"name": "TODO\\(!frontend\\)", "labels": ["todo", "frontend"]},
              {"name": "TODO\\(!documentation\\)", "labels": ["todo", "documentation"]},
              {"name": "TODO\\(!performance\\)", "labels": ["todo", "performance"]},
              {"name": "TODO\\(deadline:[0-9]{4}-[0-9]{2}-[0-9]{2}\\)", "labels": ["todo", "deadline"]},
              {"name": "FIXME", "labels": ["bug", "fix-needed"]},
              {"name": "fixme", "labels": ["bug", "fix-needed"]},
              {"name": "OPTIMIZE", "labels": ["performance"]},
              {"name": "optimize", "labels": ["performance"]},
              {"name": "HACK", "labels": ["tech-debt"]},
              {"name": "hack", "labels": ["tech-debt"]},
              {"name": "NOTE", "labels": ["documentation"]},
              {"name": "note", "labels": ["documentation"]},
              {"name": "Note", "labels": ["documentation"]}
            ]

          CLOSE_ISSUES: true
          INSERT_ISSUE_URLS: true
          AUTO_ASSIGN: 'kota-suzu'

          # 除外パターン
          IGNORE: '(^|/)node_modules/.*,(^|/)vendor/.*,.*\.lock$'

